### ISSUE TITLE
Error after updating to v6.0.1 'undefined' is not a function (evaluating 'apiCheckFactory

### ISSUE THREAD

**Issue by pauljeter** [formly-js/angular-formly#258]
After updating to the latest release (6.0.1), I get the following error when attempting to run my app:

```
  TypeError: 'undefined' is not a function (evaluating 'apiCheckFactory({
  	  output: {
  	    prefix: "angular-formly:",
  	    docsBaseUrl: __webpack_require__(3)
  	  }
  	})')
  at /bower_components/angular-formly/dist/formly.js:141
```

Am I doing something wrong?

Thanks.

**Comment by kentcdodds** [comment]
Are you loading api-check *before* you load angular-formly?

**Comment by pauljeter** [comment]
Yes. Just like your examples, jQuery => api-check => angular => angular-messages => formly
Also, if I revert to 5.2.1, everything works. No changes other than updating formly and api-check

**Comment by kentcdodds** [comment]
Thanks for checking on that. Do you think you could create an example of the issue using [this jsbin](http://jsbin.com/biqesi/edit) as a template?

**Comment by pauljeter** [comment]
Sure. Thanks for the lightning quick response. I am on a deadline, so continuing with 5.2.1 for today. I will create a jsbin example as soon as I can. BTW, attended your workshop at ng-conf. Great work.

**Comment by kentcdodds** [comment]
Thanks! Thanks for enduring the pains of upgrading. Looking forward to your example.

**Comment by kentcdodds** [comment]
I just noticed this is a small app I was upgrading and it happened because I didn't change the script tag that's loading apiCheck. In apiCheck 7.0.0, the name of the file changed from `apiCheck.js` to `api-check.js`. Make sure that you've updated the file you're loading.

**Comment by pauljeter** [comment]
That did it! Thanks. Any specific reason for changing the file name? Now I see it in the 7.0.0-beta notes in the api-check Changlog, but might want to mention that in the Formly Changlog as well.

**Comment by kentcdodds** [comment]
Good point. It's likely that most angular-formly users think little to nothing about api-check. Thanks for the feedback.

**Comment by pauljeter** [comment]
No prob. Thanks for the great form tool!
