### ISSUE TITLE
Angular v1.5x breaks select-ui integration.

### ISSUE THREAD

**Issue by alindberg** [formly-js/angular-formly#707]
I have been trying to integrate ui-select into my angular-formly application.

The example at http://jsbin.com/fuyiva/2/edit?html,js,output runs just fine on jsbin or copied to my local server.  However If you simply change angluar from 1.4.7 as on the demo page to 1.5.8 (the latest) they application will break with the following console error message:

    angular.js:13294Error: [ui.select:transcluded] http://errors.angularjs.org/1.5.8/ui.select/transcluded?p0=Expected%201%20.ui-select-match%20but%20got%20'%7B0%7D'.&p1=0

Thanks.

Alex Lindberg

**Comment by alindberg** [comment]
Updating the demo code to use 0.16.0 for ui-select fixed the issue running Angular 1.5.x

**Comment by mail2vinay** [comment]
Do we have any workaround to make it work in Angular 1.5x
how to customize the theme of select-ui.

Thank you,
Vinay

**Comment by CodeLiftSleep** [comment]
use nya-bootstrap-select it works fine

**Comment by blowsie** [comment]
https://github.com/formly-js/angular-formly/issues/441
