### ISSUE TITLE
JSPM fails

### ISSUE THREAD

**Issue by ShMcK** [formly-js/angular-formly#194]
I noticed Browserify doesn't work, I assume [JSPM](http://jspm.io/) fails for the same reason: webpack's require. 

Error: `Uncaught TypeError: __webpack_require__(...) is not a function`.

Any quick fixes?

**Comment by kentcdodds** [comment]
No quick fixes I'm afraid... I'll have to look into it...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by Antariano** [comment]
Probably related, this happens when using browserify.

```
....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\source-map-generator.js:275                                            
        throw new Error('Invalid mapping: ' + JSON.stringify({                                                                                                                                                                              
              ^                                                                                                                                                                                                                             
Error: Invalid mapping: {"generated":{"line":41230,"column":7},"source":"webpack:///webpack/universalModuleDefinition","original":{},"name":null}                                                                                           
    at SourceMapGenerator_validateMapping [as _validateMapping] (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\source
-map-generator.js:275:15)                                                                                                                                                                                                                   
    at SourceMapGenerator_addMapping [as addMapping] (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\source-map-genera
tor.js:105:14)                                                                                                                                                                                                                              
    at ....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\inline-source-map\index.js:40:15                                                          
    at Array.forEach (native)                                                                                                                                                                                                               
    at Generator.addMappings (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\inline-source-map\index.js:38:12)                                  
    at Combiner._addExistingMap (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\index.js:33:18)                                                              
    at Combiner.addFile (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\index.js:58:12)                                                                      
    at Stream.write (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\index.js:49:23)                                                                                                          
    at Stream.stream.write (....redacted....\node_modules\gulp-browserify\node_modules\browserify\node_modules\browser-pack\node_modules\through\index.js:26:11)                                                                              
    at Stream.ondata (stream.js:51:26)                                                                                                                                                                                                      
```

**Comment by kentcdodds** [comment]
Looks like another browserify issue consuming webpack generated code. Dah! This is super frustrating. What if you require the minified version? `require('angular-formly/dist/formly.min.js')`

**Comment by ShMcK** [comment]
I tried JSPM with the minified version. Different error this time:
`Uncaught TypeError: n(...) is not a function`

**Comment by jameswyse** [comment]
Ran in to this as well when I upgraded from 3.3 to 4.0.2 via Bower.

Minified has the same problem (except `__webpack_require__` is renamed to `n`)

**Comment by kentcdodds** [comment]
I'm not sure how this could happen. Could you look at the source and make sure this line still exists: https://github.com/formly-js/angular-formly/blob/master/dist/formly.js#L18 and make sure that it's passed to all the modules. This is a very odd issue. I feel like if the script runs in the browser but not with your tool, then the bug is with your tool, not the library... But I'd like to do whatever I need to help this work for you guys.

**Comment by ShMcK** [comment]
You're right, there are no references to `webpack` loaded from minified version. When I remove the reference to sourcemaps in `formly.min.js`, the problem persists as well.

Is there a version of formly that doesn't rely on `webpack` module loading? 

I prefer JSPM as it is just a simple extension of NPM & Bower, tools most people are already familiar with. The learning curve is minutes. 

Perhaps the issue is JSPM providing better webpack support...

**Comment by jameswyse** [comment]
Started debugging this today and I'd totally forgotten that I moved all my vendor deps to a simple concat task (after having similar issues with other libraries not working)

It may have just been that something was wrong with the 4.0.2 build, because I upgraded to 4.0.6 today and it works just fine! (well, after adding `api-check/dist/apiCheck.js` to my vendor.js)

@ShMcK have you tried v4.0.6?

**Comment by ShMcK** [comment]
Significant step forward. Angular-formly@4.0.6 loads, but then, sadly, crashes on api-check@6.0.10.

```
Failed to load resource: net::ERR_CONNECTION_REFUSED. 
Error loading "bower:api-check@6.0.10"
```

I'm not sure why it fails to load as all paths look fine.

The server fails with: 
```
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by jameswyse** [comment]
I'm not familiar with JSPM, but that error indicates that it tried to connect to a server somewhere and the DNS lookup failed.

I had to install `api-check` manually with bower, so maybe try that? `jspm install bower:api-check`

**Comment by ShMcK** [comment]
It's strange, all the paths are fine but the `es6-module-loader` gives a DSN error.

I'll try updating the es6-module-loader & traceur to see if a fix has been incorporated. 

I would really like to use angular-formly on this new project!

**Comment by kentcdodds** [comment]
I would like you to be able to use angular-formly on your new project too! Let me know what I can do to help.

**Comment by kentcdodds** [comment]
@ShMcK, did you get it working? Does this issue need to remain open?

**Comment by ShMcK** [comment]
I think it's fair to assume its a bigger JSPM or ES6ModuleLoader issue, as it works fine with NPM. Not library specific.

**Comment by kentcdodds** [comment]
Ok, please let me know if there's anything that I can do on my end to make this work. Good luck!
